#!/usr/bin/env Rscript

###############################################################################
## Project ID: GB-SB-1467
## Authors: Ayushi Agrawal
##
## Script Goal: Run DoubletFinder to find doublets in snRNA-seq data
##
## Usage example:
## 02a_doubletfinder.R \
## --cellranger_h5 filtered_feature_bc_matrix.h5 \
## --cellbender_h5 cellbender_feature_bc_matrix_filtered.h5 \
## --doublet_rate_estimate 10X_doublet_rate_estimation.csv \
## --mt_genes_pattern "^mt-" \
## --percent_mt_cutoff 0.20 \
## --nfeature_min_cutoff 750 \
## --output 04c_pre_post_ambient_removal/sample_1
##
## Run "Rscript 02a_doubletfinder.R --help" for more information
###############################################################################


# Get input arguments -----------------------------------------------------
library(optparse)
option_list <- list(
  make_option("--cellranger_h5",
              action = "store", default = NA, type = "character",
              help = paste0("cellranger count H5 file that was used as input for cellbender ", 
                            "(atleast one of cellbender_h5 or cellranger_h5 should be provided)")
  ),
  make_option("--cellbender_h5",
              action = "store", default = NA, type = "character",
              help = paste0("cellbender filtered H5 file ", 
                            "(atleast one of cellbender_h5 or cellranger_h5 should be provided)")
  ),
  make_option("--doublet_rate_estimate",
              action = "store", default = NA, type = "character",
              help = "doublet rate estimation table from the 10x (csv format)"
  ),
  make_option("--mt_genes_pattern",
    action = "store", default = "^mt-", type = "character",
    help = "mitochondrial genes pattern (default is ^mt- for mouse)"
  ),
  make_option("--percent_mt_cutoff",
              action = "store", default = 0.25, type = "numeric",
              help = "quality control cutoff for percentage of mitochondrial genes"
  ),
  make_option("--nfeature_min_cutoff",
              action = "store", default = 200, type = "numeric",
              help = "quality control cutoff for minimum value of nFeature_RNA"
  ),
  make_option("--output",
              action = "store", default = NA, type = "character",
              help = "Output directory (required)"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

# Check if required args are provided
if ((is.na(opt$cellranger_h5) && is.na(opt$cellbender_h5)) || is.na(opt$output) || is.na(opt$doublet_rate_estimate)) {
  stop("Missing one or more required arguments")
}

# Load required packages
library(Seurat)
library(scCustomize)
library(tidyverse)
library(DoubletFinder)
library(ggpubr)

# create the results folders
if (!(dir.exists(opt$output))) {
  dir.create(opt$output)
}

# Set seed
set.seed(42)

#increase RAM usage so the futurized Seurat functions... 
#can access larger global variables
options(future.globals.maxSize = 8000 * 1024^2)

# Prevent the Rplots.pdf from being autogenerated
pdf(NULL)

# Load data based on provided options
pre <- post <- NULL
if (!is.na(opt$cellranger_h5)) {
  pre <- Read10X_h5(opt$cellranger_h5)
}

if (!is.na(opt$cellbender_h5)) {
  post <- Read_CellBender_h5_Mat(opt$cellbender_h5)
}

# Load raw and filtered data, keeping only the cells that are present in both matrices
if (!is.null(pre) && !is.null(post)) {
  dual_seurat <- Create_CellBender_Merged_Seurat(
    raw_cell_bender_matrix = post,
    raw_counts_matrix = pre,
    raw_assay_name = "RAW"
  )
  # Remove raw data
  dual_seurat[["RAW"]] <- NULL
} else {
  if (!is.null(pre)) {
    dual_seurat <- CreateSeuratObject(pre)
    print("Cell Ranger H5 provided.")
  } else if (!is.null(post)) {
    dual_seurat <- CreateSeuratObject(post)
    print("Cell Bender H5 provided.")
  }
}

# Remove unnecessary objects
rm(pre, post)

print(paste0("Using mitochondrial gene pattern: ", opt$mt_genes_pattern))

# Calculate the percentage of mitochondrial genes
dual_seurat[["percent.mt"]] <- PercentageFeatureSet(dual_seurat, pattern = opt$mt_genes_pattern)

# Filter using QC cutoffs
seurat_filtered <- subset(dual_seurat,
                          subset = nFeature_RNA > opt$nfeature_min_cutoff & 
                            nFeature_RNA < quantile(dual_seurat$nFeature_RNA, 0.99) &
                            percent.mt < opt$percent_mt_cutoff)

# Pre and post filter cell counts
out_df <- tibble(
  prefilter_ncells = ncol(dual_seurat),
  postfilter_ncells = ncol(seurat_filtered)
)

rm(dual_seurat)

## Pre-process Seurat object (sctransform)
seurat_filtered <- SCTransform(seurat_filtered)
seurat_filtered <- RunPCA(seurat_filtered)

# Elbow plot to save later
p1 <- ElbowPlot(seurat_filtered) + ggtitle(basename(opt$output))

seurat_filtered <- RunUMAP(seurat_filtered, dims = 1:15)


## pK Identification (no ground-truth) ---------------------------------------------------------------
sweep.res.list_pbmc <- paramSweep(seurat_filtered, PCs = 1:15, sct = T)
sweep.stats_pbmc <- summarizeSweep(sweep.res.list_pbmc, GT = FALSE)
bcmvn <- find.pK(sweep.stats_pbmc)

# pK omptimization plot
p2 <- ggplot(bcmvn, aes(pK, BCmetric, group = 1)) +
  geom_point() +
  geom_line() +
  theme_pubclean() +
  scale_x_discrete(guide = guide_axis(angle = 45)) + 
  ggtitle(basename(opt$output))

pK <- bcmvn %>% # select the pK that corresponds to max bcmvn to optimize doublet detection
  filter(BCmetric == max(BCmetric)) %>%
  select(pK)
pK <- as.numeric(as.character(pK[[1]]))


## Homotypic Doublet Proportion Estimate -------------------------------------------------------------
annotations <- seurat_filtered@meta.data$seurat_clusters
homotypic.prop <- modelHomotypic(annotations)

# calculate the doublet formation rate
doublet_rate_estimate_table <- read.csv(opt$doublet_rate_estimate)

if (nrow(seurat_filtered@meta.data) >= 10000) {
  recovered_cells <- 10000
} else if (nrow(seurat_filtered@meta.data) <= 500) {
  recovered_cells <- 500
} else{
  recovered_cells <- round(nrow(seurat_filtered@meta.data), -3)
}
print(paste0("Recovered cells for doublet estimation rate: ", recovered_cells))

doublet_rate <- (doublet_rate_estimate_table$multiplet_rate[
  doublet_rate_estimate_table$number_of_cells_recovered == recovered_cells])/100
print(paste0("Doublet rate: ", doublet_rate))


nExp_poi <- round(doublet_rate * nrow(seurat_filtered@meta.data))
nExp_poi.adj <- round(nExp_poi * (1 - homotypic.prop))


# Run doubletFinder
seurat_filtered <- doubletFinder(seurat_filtered,
                                 PCs = 1:15,
                                 pN = 0.25,
                                 pK = pK,
                                 nExp = nExp_poi.adj,
                                 reuse.pANN = NULL, 
				 sct = T
)

meta_label <- paste0("DF.classifications_0.25_", pK, "_", nExp_poi.adj)

# Visualize doublets
p3 <- DimPlot(seurat_filtered,
              reduction = "umap",
              group.by = meta_label
) + ggtitle(paste0(meta_label, " for ", basename(opt$output)))

p4 <- DimPlot(seurat_filtered,
              reduction = "umap",
              group.by = meta_label,
              split.by = meta_label
) + NoLegend() + ggtitle(paste0(meta_label, " for ", basename(opt$output)))

p5 <- FeaturePlot(seurat_filtered, 
                  raster = FALSE, 
                  order = TRUE, 
                  label = FALSE, 
                  features="nCount_RNA", 
                  reduction = "umap"
) + ggtitle(paste0("nCount_RNA for ", basename(opt$output)))

p6 <- FeaturePlot(seurat_filtered, 
                  raster = FALSE, 
                  order = TRUE, 
                  label = FALSE, 
                  features="nCount_SCT", 
                  reduction = "umap"
) + ggtitle(paste0("nCount_SCT for ", basename(opt$output))) 

# Number of singlets and doublets
singlet_num <- table(seurat_filtered@meta.data[[meta_label]]) %>%
  as.data.frame() %>%
  t() %>%
  as.data.frame() %>%
  as_tibble()
singlet_num <- setNames(singlet_num[-1, ], singlet_num[1, ])

# Pre and post metrics df
out_df <- cbind(out_df, singlet_num)

seurat_filtered <- seurat_filtered[, which(FetchData(seurat_filtered,
                                                     vars = meta_label
                                                     ) == "Singlet")]

saveRDS(
  object = seurat_filtered,
  file = paste0(
    opt$output,
    "/",
    basename(opt$output),
    "_post_doublet_removal.rds"
  )
)

# Output table of pre and post counts
write_csv(out_df,
          file = paste0(
            opt$output,
            "/",
            basename(opt$output),
            "_QC_metrics_and_doublets_removed.csv"
          )
)
# Print table for logs
print(out_df)

# Output plots
pdf(paste0(opt$output, "/", basename(opt$output),"_doublet_removal_plots.pdf"))

for (i in 1:length(list(p1, p2, p3, p4, p5, p6))) {
  # add logic to make 2nd plot 1.3 times wider
  if (i == 2) {
    p2 <- p2 + theme(aspect.ratio = 1.3)
    print(p2)
  } else {
    print(get(paste0("p", i)))
  }
}

dev.off()


# Write session info
writeLines(
  capture.output(sessionInfo()),
  file.path(opt$output, "sessionInfo_doublet_finder.txt")
)

#record logs
print("***** Script completed! *****")


########################## END ########################## 
