#!/usr/bin/env Rscript

###############################################################################
## Project ID: GB-SB-1467
## Authors: Natalie Elphick, Ayushi Agrawal
##
## Script Goal: Generate plots of QC metrics for a series of scRNA-seq samples
##
## Usage example:
## 03a_visualize_qc_metrics.R \                 
## --input_preqc 01_cellranger_count \  # Folder with cellranger count outputs
## --input_postqc 02_doublet_removal \  # Folder with doublet finder outputs
## --output 03_visualize_qc_metrics     # Ouput directory
##
## Run "Rscript 03a_visualize_qc_metrics.R --help" for more information
###############################################################################

# Get input arguments -----------------------------------------------------
library(optparse)
option_list <- list(
  make_option(c("-i", "--input_preqc"),
              action = "store", default = NA, type = "character",
              help = "Directories containing outputs from cellranger count"
  ),
  make_option(c("-q", "--input_postqc"),
              action = "store", default = NA, type = "character",
              help = "Directories containing outputs from doublet finder (post qc)"
  ),
  make_option(c("-o", "--output"),
              action = "store", default = NA, type = "character",
              help = "Output directory, will create if it doesn't exist (required)"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

# Check if required args are provided
if (is.na(opt$input_preqc) | is.na(opt$input_postqc) | is.na(opt$output)) {
  stop("Missing one or more required arguments")
}

# Load required packages
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(magrittr)
library(Seurat)

set.seed(42)
options(warn = 1)

# create the results folders
if (!(dir.exists(opt$output))) {
  dir.create(opt$output, recursive= T)
}

# Prevent the Rplots.pdf from being autogenerated
pdf(NULL)

# Get a list of the sample directories
samples <- read.csv(opt$input_preqc)


# Read in the data -------------------------------------------------------------------------
plot_list_preqc <- NULL
plot_list_postqc <- NULL
obj_list_preqc <- NULL
obj_list_postqc <- NULL

for (sam_path in samples[,1]) {
  sam <- basename(sam_path)
  ##### pre qc plots and data #####
  sample_path_pre <- file.path(sam_path, "count/sample_filtered_feature_bc_matrix.h5")
  print(sample_path_pre)
  sample_data <- Read10X_h5(filename = sample_path_pre)
  sample_obj <- CreateSeuratObject(counts = sample_data)
  rm(sample_data)
  sample_obj[["percent.mt"]] <- PercentageFeatureSet(sample_obj, pattern = "^mt-")
  pl <- VlnPlot(sample_obj,
                features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                ncol = 3) &
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          title = element_text(size = 9),
          plot.margin = margin(t = 10, b = 10, r = 3, l = 3))
  plot_list_preqc[[sam]] <- pl
  sample_obj$sample <- sam
  sample_obj$qc <- "pre_qc"
  obj_list_preqc[[sam]] <- sample_obj
  
  ##### post qc plots and data #####
  sample_file_post <- file.path(opt$input_postqc, sam, paste0(sam, "_post_doublet_removal.rds"))
  print(sample_file_post)
  sample_obj <- readRDS(sample_file_post)
  pl <- VlnPlot(sample_obj,
                features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                ncol = 3) &
    theme(axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          title = element_text(size = 9),
          plot.margin = margin(t = 10, b = 10, r = 3, l = 3))
  plot_list_postqc[[sam]] <- pl
  sample_obj$sample <- sam
  sample_obj$qc <- "post_qc"
  obj_list_postqc[[sam]] <- sample_obj
}

# merge the data 
input_rds_preqc <- merge(obj_list_preqc[[1]],
                         y = unlist(obj_list_preqc[2:length(obj_list_preqc)]),
                         add.cell.ids = names(obj_list_preqc),
                         merge.data = FALSE
)
rm(obj_list_preqc)

input_rds_postqc <- merge(obj_list_postqc[[1]],
                          y = unlist(obj_list_postqc[2:length(obj_list_postqc)]),
                          add.cell.ids = names(obj_list_postqc),
                          merge.data = FALSE
)
rm(obj_list_postqc)




# QC metrics plots --------------------------------------------------------------------------
pre_qc_plots <- ggarrange(
  plotlist = plot_list_preqc,
  ncol = 2,
  nrow = ceiling(length(plot_list_preqc) / 2),
  labels = names(plot_list_preqc),
  vjust = 1.3,
  label.x = .4,
  legend = "none"
)

ggsave(filename = file.path(opt$output,"pre_qc_metrics.pdf"),
       plot = pre_qc_plots,
       height = ceiling(length(plot_list_preqc) / 2) * 3,
       width = 8, limitsize = FALSE)

post_qc_plots <- ggarrange(
  plotlist = plot_list_postqc,
  ncol = 2,
  nrow = ceiling(length(plot_list_postqc) / 2),
  labels = names(plot_list_postqc),
  vjust = 1.3,
  label.x = .4,
  legend = "none"
)

ggsave(filename = file.path(opt$output,"post_qc_metrics.pdf"),
       plot = post_qc_plots,
       height = ceiling(length(plot_list_postqc) / 2) * 3,
       width = 8, limitsize = FALSE)




# Merged version of the qc metrics plots ----------------------------------------------------------

# Create a data frame with one row for the bar
data <- data.frame(Label = "Pre QC", Value = 1)
# Create the horizontal bar plot with text
p1 <- ggplot(data, aes(x = 0, y = Value, label = Label)) +
  geom_bar(stat = "identity", width = 1, fill = "grey") +
  geom_text(aes(x = 0, y = Value), color = "white", size = 10, 
            position=position_stack(vjust=0.5)) +
  theme_void()  # Remove axes and labels

data <- data.frame(Label = "Post QC", Value = 1)
p2 <- ggplot(data, aes(x = 0, y = Value, label = Label)) +
  geom_bar(stat = "identity", width = 1, fill = "grey") +
  geom_text(aes(x = 0, y = Value), color = "white", size = 10, 
            position=position_stack(vjust=0.5)) +
  theme_void()

p3 <- VlnPlot(input_rds_preqc,
              features = "percent.mt",
              group.by = "sample",pt.size = 0) &
  theme_bw() &
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size = 28)) &
  coord_flip() &
  scale_y_continuous(sec.axis = dup_axis()) 

p4 <- VlnPlot(input_rds_preqc,
              features = "nCount_RNA",
              group.by = "sample",pt.size = 0) &
  theme_bw() &
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 28)) &
  coord_flip() &
  scale_y_continuous(sec.axis = dup_axis()) 

p5 <- VlnPlot(input_rds_preqc,
              features = "nFeature_RNA",
              group.by = "sample",pt.size = 0) &
  theme_bw() &
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 28)) &
  coord_flip() &
  scale_y_continuous(sec.axis = dup_axis()) 

p6 <- ggplot() + theme_void()

p7 <- VlnPlot(input_rds_postqc,
              features = "percent.mt",
              group.by = "sample",pt.size = 0) &
  theme_bw() &
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        text = element_text(size = 28)) &
  coord_flip() &
  scale_y_continuous(sec.axis = dup_axis()) 

p8 <- VlnPlot(input_rds_postqc,
              features = "nCount_RNA",
              group.by = "sample",pt.size = 0) &
  theme_bw() &
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 28)) &
  coord_flip() &
  scale_y_continuous(sec.axis = dup_axis()) 

p9 <- VlnPlot(input_rds_postqc,
              features = "nFeature_RNA",
              group.by = "sample",pt.size = 0) &
  theme_bw() &
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        text = element_text(size = 28)) &
  coord_flip() &
  scale_y_continuous(sec.axis = dup_axis()) 

ggarrange(p1,p1,p1,p6,p2,p2,p2,
          p3,p4,p5,p6,p7,p8,p9,
          nrow=2,
          ncol = 7,
          widths = c(1.25,1,1,0.3,1.25,1,1),
          heights = c(0.1,1))%>%
  ggsave(filename =  file.path(opt$output,"merged_qc_metrics.pdf"),
         plot = .,
         width = 40,
         height = ceiling(length(plot_list_postqc) / 2) * 3,
         limitsize = FALSE)




# Cell counts pre and post QC --------------------------------------------------------------------
results <- table(input_rds_preqc@meta.data[["sample"]]) %>%
  as.data.frame() 
colnames(results) <- c("Sample", "cellranger_counts")
post_qc <- table(input_rds_postqc@meta.data[["sample"]]) %>%
  as.data.frame() 
rownames(post_qc) <- post_qc$Var1
results$post_qc_counts <- post_qc$Freq[results$Sample]
results <- results %>%
  mutate(Percent_filtered = round(((cellranger_counts-post_qc_counts)/cellranger_counts)*100,
                                  digits = 2))

plotdata <- results %>%
  select(Sample,cellranger_counts,post_qc_counts, Percent_filtered) %>%
  pivot_longer(!Sample, values_to = "Cells") %>%
  mutate(name = ifelse(name == "cellranger_counts","Pre-QC",
                       ifelse(name == "post_qc_counts","Post-QC","Percent_filtered")))

ggplot(data =plotdata[plotdata$name != "Percent_filtered",] ,
       aes(x = Sample, y = Cells, fill = factor(name, levels=c("Pre-QC","Post-QC")))) +
  geom_bar(stat = "identity", position = "dodge") + 
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5),
    legend.title = element_blank()
  ) +
  xlab("Sample") +
  ylab("Number of cells") +
  ggtitle("Number of cells per sample before and after QC")

write_csv(x = results,file = file.path(opt$output,"pre_post_qc_metrics.csv"))
ggsave(filename = file.path(opt$output,"pre_post_qc_cell_counts.png"),
       dpi = 300,
       units = "in",
       width = 14,
       height = 5,
       limitsize = FALSE)




# Write session info
writeLines(
  capture.output(sessionInfo()),
  file.path(opt$output, "sessionInfo.txt")
)

# record logs
print("***** Script completed! *****")

########################## END ##########################
