#!/usr/bin/env Rscript

###############################################################################
## Project ID: GB-SB-1467
## Authors: Ayushi Agrawal
##
## Script Goal: ‘Sketching’ to subsample cells from large datasets while 
##               preserving rare populations
##
## Usage example:
## Rscript 05a_sketch_data.R \
##  --input 'input_seurat_object.RDS' \  # Seurat object with multiple samples
##  --output '/output_directory' \       # Location for output files
##  --genotypes_to_keep "E2,E3"          # Comma-separated list of genotypes to keep
##  --mode "scRNA" \                     # Is the input scRNA or CyTOF?
##  --output_prefix "outputs_scRNA_" \   # Prefix for output files
##  --cores 4                            # Number of cores to use
##  --sketch_percent 25                  # Percent of cells to use for sketching
##
## Run "Rscript 05a_sketch_data.R --help" for more information
###############################################################################


# Get input arguments -----------------------------------------------------
library(optparse)
option_list <- list(
  make_option(c("-i", "--input"),
              action = "store", default = NA, type = "character",
              help = "Input Seurat object in RDS format (required)"
  ),
  make_option(c("-o", "--output"),
              action = "store", default = NA, type = "character",
              help = "Output directory, will create if it doesn't exist (required)"
  ),
  make_option(c("-c", "--cores"),
              action = "store", default = 2, type = "numeric",
              help = "Number of cores to use, [default %default]"
  ),
  make_option(c("--mode"),
              action = "store", default = NA, type = "character",
              help = "Input data type vaid options are 'scRNA' or 'CyTOF' (required)"
  ),
  make_option(c("--output_prefix"),
              action = "store",
              default = "optimize_resolution",
              type = "character",
              help = "Prefix for output files, [default %default]"
  ),
  make_option("--celltype_subset",
              action = "store", default = NA, type = "numeric",
              help = "If provided, the input will be subset to inlcude only the nth celltype (optional)",
  ),
  make_option("--annotation_file",
              action = "store", default = NA, type = "character",
              help = "Cell type annotation for the input RDS seurat clusters (optional)"
  ),
  make_option(c("--cluster_subset"),
              action = "store", default = NA, type = "character",
              help = "If provided, the input will be subset by seurat clusters to include provided clusters (optional)"
  ),
  make_option("--genotypes_to_keep",
              action = "store", default = NA, type = "character",
              help = "Comma-separated list of genotype(s) to keep (optional)"
  ),
  make_option("--sketch_percent",
              action = "store", default = 25, type = "numeric",
              help = "Percent of cells to use for sketching - a number between 0-100. (optional)"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

# Check if required args are provided
if (is.na(opt$input) | is.na(opt$output) | is.na(opt$mode)) {
  stop("Missing one or more required arguments")
}

# Check if mode argument is a valid option
if (opt$mode != "scRNA" & opt$mode != "CyTOF") {
  stop("Invalid option for --mode, must be scRNA or CyTOF")
}




# Load required packages --------------------------------------------------
library(tidyverse)
library(Seurat)
library(ranger)
library(cluster)
library(foreach)
library(doParallel)
library(future)


# Prevent the Rplots.pdf from being autogenerated
pdf(NULL)

# Leave one core free
nCores <- opt$cores - 1

# Register the cluster for foreach
registerDoParallel(cores = nCores)
getDoParWorkers()
getDoParName()

set.seed(332)
options(warn = 1)
options(future.globals.maxSize = 8000 * 1024^2)




# Functions ---------------------------------------------------------------
# check_size: Checks if input Seurat object is small enough to run clustOpt
check_size <- function(input, verbose = TRUE) {
  if (!methods::is(input, "Seurat")) {
    stop("Input must be a Seurat object")
  }
  if (ncol(input) >= 2E5) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}

# leverage_sketch: Uses leverage score based sampling to reduce the size of the
# input Seurat object and create a sketch assay using this subsample
leverage_sketch <- function(input, sketch_size, verbose = TRUE) {
  if (is.na(sketch_size)) {
    if (verbose) {
      message("No sketch_size specified, defaulting to 10% of cells")
    }
    sketch_size <- ncol(input) * 0.1
  }
  
  input <- Seurat::NormalizeData(input)
  input <- Seurat::FindVariableFeatures(input)
  input <- Seurat::SketchData(
    object = input,
    ncells = sketch_size,
    method = "LeverageScore",
    sketched.assay = "sketch"
  )
  Seurat::DefaultAssay(input) <- "sketch"
  # Return only the sketch assay
  input <- Seurat::DietSeurat(input, assays = "sketch")
}




# Prepare the data -------------------------------------------------------------
# Read in the Seurat object
input_rds <- readRDS(opt$input)
print("Input RDS:")
print(input_rds)

# If the cluster_subset argument is provided, subset the Seurat object to 
# include only the seurat clusters provided
if (!is.na(opt$cluster_subset)) {
  temp <- strsplit(as.character(opt$cluster_subset), ',')
  cell_type_clusters <- as.numeric(as.character(unlist(temp)))
  print(cell_type_clusters)
  temp_rds <- subset(input_rds, idents = cell_type_clusters)
  temp_rds$seurat_clusters <- droplevels(temp_rds$seurat_clusters)
  input_rds <- temp_rds
  print(input_rds)
  print(table(input_rds$seurat_clusters))
}

# subset the data by genotype if requested
if (!is.na(opt$genotypes_to_keep)) {
  # Split the comma-separated string into a character vector
  requested_genotypes <- unlist(strsplit(opt$genotypes_to_keep, ","))
  requested_genotypes <- trimws(requested_genotypes)  # remove any extra whitespace
  
  # Check if all requested genotypes are in the object
  existing_genotypes <- unique(input_rds$Genotype)
  if (!all(requested_genotypes %in% existing_genotypes)) {
    # Identify missing genotypes for a clearer error message
    missing_genotypes <- requested_genotypes[!(requested_genotypes %in% existing_genotypes)]
    stop(paste(
      "ERROR: The following genotype(s) are not found in the dataset:", 
      paste(missing_genotypes, collapse = ", ")
    ))
  }
  
  # Subset the Seurat object to keep only the requested genotypes
  input_rds <- subset(input_rds, subset = Genotype %in% requested_genotypes)
}

# If the subset arguments are provided, subset the Seurat object
if (!is.na(opt$celltype_subset) & !is.na(opt$annotation_file)) {
  annotations_df <- read.csv(opt$annotation_file)
  celltypes <- sort(unique(annotations_df$type))
  print(paste0("Subsetting input data for celltype: ", celltypes[opt$celltype_subset]))
  cluster_vector <- annotations_df$cluster[annotations_df$type == celltypes[opt$celltype_subset]]
  temp_rds <- subset(input_rds, subset = seurat_clusters %in% cluster_vector)
  temp_rds$seurat_clusters <- droplevels(temp_rds$seurat_clusters)
  input_rds <- temp_rds
  print("Data after subsetting for celltype:")
  print(input_rds)
  print(table(input_rds$seurat_clusters))
  opt$output <- file.path(opt$output, gsub(" ", "_", celltypes[opt$celltype_subset]))
  opt$output_prefix <- paste0(opt$output_prefix, "_", gsub(" ", "_", celltypes[opt$celltype_subset]))
  rm(temp_rds)
} 




# sketch the data --------------------------------------------------------------
output_postfix <- NA

if (opt$mode == "scRNA") {
  # Clear any previous normalizations
  Seurat::DefaultAssay(input_rds) <- "RNA"
  input_rds <- Seurat::DietSeurat(input_rds, assays = "RNA")
  
  # calcualte sketch size
  opt$sketch_size <- (opt$sketch_percent * ncol(input_rds)) / 100
  
  if (check_size(input_rds) && !is.na(opt$sketch_size)) {
    message("Sketching input data")
    input_rds <- leverage_sketch(input_rds, opt$sketch_size)
    output_postfix <- "_sketched_data.rds"
  } else {
    message("Input is small enough to run with all cells")
    output_postfix <- "_orig_data.rds"
  }
} else {
  message("No sketching was performed for CyTOF data")
}




# Save RDS object --------------------------------------------------------
# create the results folders and all parent folders if they don't exist
if (!(dir.exists(opt$output))) {
  dir.create(opt$output, recursive = TRUE)
}


saveRDS(
  input_rds,
  file = paste0(
    opt$output,
    "/",
    opt$output_prefix,
    output_postfix
  )
)



writeLines(
  capture.output(sessionInfo()),
  file.path(opt$output, "sessionInfo.txt")
)


# END