#!/usr/bin/env Rscript

###############################################################################
## Project ID: GB-SB-1467
## Authors: Reuben Thomas, Natalie Elphick, Ayushi Agrawal
##
## Script Goal: Optimize resolution parameter; check silhouette score
## distribution and decide the optimal resolution
##
## Usage example:
## Rscript 05b_cluster_resolution_optimization_per_sample.R \
##  --input 'input_seurat_object.RDS' \  # Seurat object with multiple samples
##  --output '/output_directory' \       # Location for output files
##  --mode "scRNA" \                     # Is the input scRNA or CyTOF?
##  --output_prefix "outputs_scRNA_" \   # Prefix for output files
##  --ndim 20 \                          # Number of PCs to use
##  --metadata "sample"                  # Name of sample identifier
##  --cluster_subset "2,3"               # Clusters to subset and optimize for
##  --cores 4                            # Number of cores to use
##  --sample 1                           # The nth sample to use as test data
##
## Run "Rscript 05b_cluster_resolution_optimization_per_sample.R --help" for more information
###############################################################################


# Get input arguments -----------------------------------------------------
library(optparse)
option_list <- list(
  make_option(c("-i", "--input"),
              action = "store", default = NA, type = "character",
              help = "Input Seurat object in RDS format (required)"
  ),
  make_option(c("-o", "--output"),
              action = "store", default = NA, type = "character",
              help = "Output directory, will create if it doesn't exist (required)"
  ),
  make_option(c("-c", "--cores"),
              action = "store", default = 2, type = "numeric",
              help = "Number of cores to use, [default %default]"
  ),
  make_option(c("--mode"),
              action = "store", default = NA, type = "character",
              help = "Input data type vaid options are 'scRNA' or 'CyTOF' (required)"
  ),
  make_option(c("--output_prefix"),
              action = "store",
              default = "optimize_resolution",
              type = "character",
              help = "Prefix for output files, [default %default]"
  ),
  make_option(c("-n", "--ndim"),
              action = "store", default = NA, type = "numeric",
              help = "Number of principal components to use (required)"
  ),
  make_option(c("-m", "--metadata"),
              action = "store", default = NA, type = "character",
              help = "The metadata value for sample in the Seurat object (required)",
  ),
  make_option(c("-s", "--sample"),
              action = "store", default = NA, type = "numeric",
              help = "The nth sample in the Seurat object to use as test data (required)",
  ),
  make_option(c("--cluster_subset"),
              action = "store", default = NA, type = "character",
              help = "If provided, the input will be subset by seurat clusters to include provided clusters"
  ),
  make_option("--within_batch_var",
              action = "store", default = NA, type = "character",
              help = "The metadata value for a batching variable that if provided, 
    will be used to train the model on samples within the same batch. Only works if samples are not spread
    across batches (optional)"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

# Check if required args are provided
if (is.na(opt$metadata) | is.na(opt$input) | is.na(opt$output) | is.na(opt$ndim) | 
    is.na(opt$mode) | is.na(opt$sample)) {
  stop("Missing one or more required arguments")
}

# Check if mode argument is a valid option
if (opt$mode != "scRNA" & opt$mode != "CyTOF") {
  stop("Invalid option for --mode, must be scRNA or CyTOF")
}
print("---------- Input parameters")
print(opt)




# Load required packages --------------------------------------------------
library(tidyverse)
library(Seurat)
library(ranger)
library(cluster)
library(foreach)
library(doParallel)
library(future)


# Prevent the Rplots.pdf from being autogenerated
pdf(NULL)

# Leave one core free
nCores <- opt$cores - 1

# Register the cluster for foreach
registerDoParallel(cores = nCores)
getDoParWorkers()
getDoParName()

set.seed(332)
options(warn = 1)
options(future.globals.maxSize = 20 * 1024^3)


# create the results folders and all parent folders if they don't exist
opt$output <- file.path(opt$output, "per_sample_results")
if (!(dir.exists(opt$output))) {
  dir.create(opt$output, recursive = TRUE)
}


# Functions ---------------------------------------------------------------
# get_valid_samples: This function checks if there are at least 
# 3 samples with 100 or more cells. If this criterion is met, the function 
# returns the sample names that have at least 100 cells. If the criteria fails,
# NULL is returned and a warning is issued.
get_valid_samples <- function(input, subject_ids) {
  
  # Summarize the number of cells per sample
  sample_summary <- input@meta.data %>%
    group_by(!!sym(subject_ids)) %>% # group by using specified subject_ids column
    summarize(cell_count = n(), .groups = "drop") %>%
    ungroup()
  
  # Filter samples to include only those with at least 100 cells
  sufficient_samples <- sample_summary %>%
    filter(cell_count >= 100) 
  
  # Check if there are at least 3 samples with >= 100 cells
  if (nrow(sufficient_samples) < 3) {
    warning("There are fewer than 3 samples with >= 100 cells.")
    return(NULL) # Return NULL if the criterion is not met
  }
  
  # Retrieve the sample names that meet the requirement
  valid_samples <- sufficient_samples %>%
    pull(!!sym(subject_ids))
  
  # Return the list of valid sample names 
  message("There are sufficient samples. Returning the sample names that meet the criteria.")
  return(valid_samples)
}

# prep_train: Prepare training data for random forest
prep_train <- function(input,
                       subject_ids,
                       dtype = "scRNA",
                       within_batch = NA,
                       test_id) {
  if (dtype == "scRNA") {
    # If within_batch is provided, then use only training samples from the
    # same batch
    if (!is.na(within_batch)) {
      # Get the batch of test_id
      this_batch <- input@meta.data |>
        dplyr::filter(get(subject_ids) == test_id) |>
        dplyr::pull(get(within_batch)) |>
        unique()
      
      if (length(this_batch) > 1) {
        stop("More than one batch found for this sample")
      }
      
      train_cells <- input@meta.data |>
        dplyr::filter(get(subject_ids) != test_id &
                        get(within_batch) == this_batch) |>
        rownames()
      train_seurat <- subset(input, cells = train_cells)
      
      # Normalize the training samples
      train_seurat <- Seurat::SCTransform(train_seurat,
                                          assay = Seurat::DefaultAssay(train_seurat),
                                          verbose = FALSE
      )
      train_seurat <- Seurat::DietSeurat(train_seurat, assays = "SCT")
      return(train_seurat)
    } else {
      # Return all other samples
      Seurat::Idents(input) <- subject_ids
      train_cells <- Seurat::WhichCells(
        object = input,
        idents = test_id,
        invert = TRUE
      )
      train_seurat <- subset(input, cells = train_cells)
      # Normalize the training samples
      train_seurat <- Seurat::SCTransform(train_seurat,
                                          assay = Seurat::DefaultAssay(train_seurat),
                                          verbose = FALSE
      )
      train_seurat <- Seurat::DietSeurat(train_seurat, assays = "SCT")
      return(train_seurat)
    }
  } else {
    if (!is.na(within_batch)) {
      # Get the batch of test_id
      this_batch <- input@meta.data |>
        dplyr::filter(get(subject_ids) == test_id) |>
        dplyr::pull(get(within_batch)) |>
        unique()
      
      if (length(this_batch) > 1) {
        stop("More than one batch found for this sample")
      }
      
      train_cells <- input@meta.data |>
        dplyr::filter(get(subject_ids) != test_id &
                        get(within_batch) == this_batch) |>
        rownames()
      train_seurat <- subset(input, cells = train_cells)
      return(train_seurat)
    } else {
      # Return all other samples
      Seurat::Idents(input) <- subject_ids
      train_cells <- Seurat::WhichCells(
        object = input,
        idents = test_id,
        invert = TRUE
      )
      train_seurat <- subset(input, cells = train_cells)
      return(train_seurat)
    }
  }
}

# prep_test: Prepare test data for random forest
prep_test <- function(input,
                      subject_ids,
                      dtype = "scRNA",
                      test_id) {
  if (dtype == "scRNA") {
    Seurat::Idents(input) <- subject_ids
    test_cells <- Seurat::WhichCells(object = input, idents = test_id)
    test_seurat <- subset(input, cells = test_cells)
    
    test_seurat <- Seurat::SCTransform(test_seurat,
                                       assay = Seurat::DefaultAssay(test_seurat),
                                       verbose = FALSE,
                                       variable.features.n = length(rownames(test_seurat)),
                                       return.only.var.genes = FALSE,
                                       min_cells = 1
    )
    test_seurat <- Seurat::DietSeurat(test_seurat, assays = "SCT")
    
    return(test_seurat)
  } else {
    Seurat::Idents(input) <- subject_ids
    test_cells <- Seurat::WhichCells(object = input, idents = test_id)
    test_seurat <- subset(input, cells = test_cells)
    return(test_seurat)
  }
}

# project_PCA: Project Training and Test Seurat Objects onto Principal Components
# This function projects both training and test Seurat objects onto a set of
# principal components derived from the training data.
project_PCA <- function(train_seurat, test_seurat, ndim) {
  # Validate input
  if (!("Seurat" %in% class(train_seurat)) ||
      !("Seurat" %in% class(test_seurat))) {
    stop("Both train_seurat and test_seurat must be Seurat objects")
  }
  if (!is.numeric(ndim) || ndim <= 0) {
    stop("ndim must be a positive integer")
  }
  
  # Features present in both the training variable features and test sample
  common_features <- base::intersect(
    rownames(test_seurat@assays[["SCT"]]@scale.data),
    Seurat::VariableFeatures(train_seurat)
  )
  
  # Extract the loadings for common features from the training data
  loadings_common_features <- Seurat::Loadings(train_seurat[["pca"]]) |>
    tibble::as_tibble(rownames = "Features") |>
    dplyr::filter(Features %in% common_features) |>
    as.matrix()
  
  rownames(loadings_common_features) <- loadings_common_features[, 1]
  loadings_common_features <- loadings_common_features[, -1]
  class(loadings_common_features) <- "numeric"
  
  # Function to project data
  project_data <- function(seurat_obj) {
    scale_data <- as.matrix(seurat_obj[["SCT"]]@scale.data)[common_features, ]
    t(scale_data) %*% loadings_common_features
  }
  
  # Project the cells in the training and test data onto the PCs
  pca_train_data <- project_data(train_seurat)
  pca_test_data <- project_data(test_seurat)
  
  rm(loadings_common_features)
  
  
  # Select the number of dimensions to train with
  list(
    train_df = pca_train_data[, 1:ndim, drop = FALSE] |>
      as.data.frame(),
    test_df = pca_test_data[, 1:ndim, drop = FALSE] |>
      as.data.frame()
  )
}

# train_random_forest: Train the random forest and predict on the test sample
train_random_forest <- function(res, df_list, train_clusters, sam, num.trees) {
  
  message(paste0("Starting train_random_forest function on sample: ", sam, " for resolution: ", res))
  
  # Get cluster assignments for this res
  train_df <- df_list[[1]] |>
    dplyr::mutate(clusters = train_clusters |>
                    dplyr::select(dplyr::contains(as.character(res))) |>
                    dplyr::pull())
  
  # Train model
  rf <- ranger::ranger(as.factor(clusters) ~ .,
                       data = train_df,
                       num.trees = num.trees,
                       write.forest = TRUE,
                       num.threads = 1
  )
  rm(train_df)
  
  # Predict on the hold out sample
  predicted <- stats::predict(rf, df_list[[2]])
  predicted <- ranger::predictions(predicted)
  predicted_clusters_table <- base::table(predicted)
  rm(rf)
  sil <- calculate_silhouette_score(predicted, df_list[[2]])
  
  list(
    resolution = res,
    test_sample = sam,
    avg_width = sil$avg_width,
    cluster_avg_widths = sil$group_avg_width,
    n_predicted_clusters = length(unique(as.character(predicted))),
    min_predicted_cell_per_cluster = min(predicted_clusters_table),
    max_predicted_cell_per_cluster = max(predicted_clusters_table)
  )
}

# calculate_silhouette_score: Calculate silhouette score
calculate_silhouette_score <- function(predicted, data_frame) {
  sil <- cluster::silhouette(
    as.numeric(as.character(predicted)),
    dist(data_frame)
  )
  
  # Check if there is only one cluster
  if (class(sil) == "logical") {
    return(list(avg_width = NA, group_avg_width = NA))
  } else {
    sil_summary <- summary(sil)
    return(list(
      avg_width = sil_summary$avg.width,
      group_avg_width = mean(sil_summary$clus.avg.widths)
    ))
  }
}

# prepare_CyTOF: Prepare CyTOF data for random forest
prepare_CyTOF <- function(train_seurat, test_seurat) {
  list(
    Seurat::GetAssayData(train_seurat, slot = "counts", assay = "RNA") |>
      as.data.frame() |>
      t() |>
      tibble::as_tibble(rownames = "CellID") |>
      dplyr::select(CellID, everything()),
    Seurat::GetAssayData(test_seurat, slot = "counts", assay = "RNA") |>
      as.data.frame() |>
      t() |>
      tibble::as_tibble(rownames = "CellID") |>
      dplyr::select(CellID, everything())
  )
}


# Initialize variables & read in data -------------------------------------

# Read in the Seurat object
input_rds <- readRDS(opt$input)


# If the cluster_subset argument is provided, subset the Seurat object to 
# include only the seurat clusters provided
if (!is.na(opt$cluster_subset)) {
  temp <- strsplit(as.character(opt$cluster_subset), ',')
  cell_type_clusters <- as.numeric(as.character(unlist(temp)))
  print(cell_type_clusters)
  temp_rds <- subset(input_rds, idents = cell_type_clusters)
  temp_rds$seurat_clusters <- droplevels(temp_rds$seurat_clusters)
  input_rds <- temp_rds
  print(input_rds)
  print(table(input_rds$seurat_clusters))
}

# Set number of PCs to use
ndim <- opt$ndim

# Set range of resolutions to test
res_range <- c(seq(0.02,0.08,0.02), seq(0.1,1.2,0.1))

# Get sample information
sample_obj_id <- opt$metadata
n_samples <- length(unique(input_rds@meta.data[[sample_obj_id]]))
sample_names <- as.vector((unique(input_rds@meta.data[[sample_obj_id]])))

# Check if opt$sample is greater than n_samples
if (opt$sample > n_samples) {
  stop(paste("Error: The specified sample number (", opt$sample, 
             ") exceeds the number of available samples (", n_samples, ").", sep = ""))
}

# Get the sample name
sam <- sample_names[opt$sample]

# Get valid samples
valid_sample_names <- get_valid_samples(input = input_rds, 
                                  subject_ids = opt$metadata)
if (is.null(valid_sample_names)) {
  stop(paste0("ERROR: Unable to perform cluster resolution optimization for this data. ",
              "There are less than 3 samples with at least 100 cells."))
}

# Check if sam is a valid sample
if (!(sam %in% valid_sample_names)) {
  stop(paste("Error: The specified sample number (", opt$sample, 
             ") has fewer than 100 cells.", sep = ""))
}


# Main analysis ------------------------------------------------------------
# Get every combination of test sample and resolution
runs <- expand.grid(sam, res_range)
message(paste0(
  "Found ", nrow(runs),
  " combinations of test sample and resolution"
))



result <- NULL
message(paste0("Holdout sample: ", sam))

message(paste0("Preparing training data.."))

train <- prep_train(
  input = input_rds,
  dtype = opt$mode,
  subject_ids = opt$metadata,
  within_batch = opt$within_batch_var,
  test_id = sam
)

message(paste0("Preparing test data.."))

test <- prep_test(
  input = input_rds,
  dtype = opt$mode,
  subject_ids = opt$metadata,
  test_id = sam
)

if (opt$mode == "scRNA") {
  message(sprintf(
    "Found %d (%.2f%%) shared genes between testing and training data",
    length(intersect(
      rownames(test@assays[["SCT"]]@scale.data),
      Seurat::VariableFeatures(train)
    )),
    length(intersect(
      rownames(test@assays[["SCT"]]@scale.data),
      Seurat::VariableFeatures(train)
    )) / length(rownames(train@assays[["SCT"]]@scale.data)) * 100
  ))
}

if (opt$mode == "scRNA") {
  train <- Seurat::RunPCA(train,
                          npcs = ndim,
                          verbose = FALSE,
                          assay = "SCT"
  )
  train <- Seurat::FindNeighbors(
    object = train,
    dims = 1:ndim,
    verbose = TRUE
  )
  
  train <- Seurat::FindClusters(
    object = train,
    resolution = res_range,
    verbose = TRUE
  )
} else {
  train <- Seurat::ScaleData(train, features = NULL, verbose = verbose)
  train <- Seurat::FindVariableFeatures(train,
                                        selection.method = "vst", nfeatures = ndim
  )
  train <- Seurat::RunPCA(train,
                          npcs = ndim, approx = FALSE,
                          verbose = verbose
  )
  train <- Seurat::FindNeighbors(
    object = train, dims = 1:ndim,
    verbose = verbose
  )
  train <- Seurat::FindClusters(
    object = train, resolution = res_range,
    verbose = verbose
  )
}

message("Clustering complete..")


if (opt$mode == "scRNA") {
  train_clusters <- train@meta.data |>
    dplyr::select(dplyr::contains("SCT_snn_res"))
  
  message("Project the cells in the test data onto the train PCs..")
  
  df_list <- project_PCA(train, test, ndim)
  rm(train, test)
} else {
  train_clusters <- train@meta.data |>
    dplyr::select(dplyr::contains("RNA_snn_res"))
  
  df_list <- prepare_CyTOF(train, test)
  rm(train, test)
}

message("Run random forest for all the resolutions..")

this_result <- future.apply::future_lapply(
  rownames(runs[runs$Var1 == sam,]),
  function(i) {
    train_random_forest(
      res = runs[i, 2],
      df_list = df_list,
      train_clusters = train_clusters,
      sam = runs[i, 1],
      num.trees = 1000
    )
  },
  future.seed = TRUE
)
result <- c(result, this_result)

res_tbl <- purrr::map_df(result, .f = as.data.frame)

# Generate outputs --------------------------------------------------------

write_csv(
  x = res_tbl,
  file = paste0(
    opt$output,
    "/",
    opt$output_prefix,
    "_results_",sam,".csv"
  )
)



writeLines(
  capture.output(sessionInfo()),
  file.path(opt$output, "sessionInfo.txt")
)
print("Script completed!")


# END ---------------------------------------------------------------------