#!/usr/bin/env Rscript

###############################################################################
## Project ID: GB-SB-1467
## Authors: Ayushi Agrawal
##
## Script Goal: Compile results for optimize resolution parameter; check 
## silhouette score distribution and decide the optimal resolution
##
## Usage example:
## Rscript 05c_cluster_resolution_optimization_summarize.R  \
##  --input '/per_sample_results' \  # Location for per sample optimize resolution results
##  --output '/output_directory' \       # Location for output files
##  --output_prefix "outputs_scRNA_" \   # Prefix for output files
##
## Run "Rscript 05c_cluster_resolution_optimization_summarize.R  --help" for more information
###############################################################################


# Get input arguments -----------------------------------------------------
library(optparse)
option_list <- list(
  make_option(c("-i", "--input"),
              action = "store", default = NA, type = "character",
              help = "Input directory with per sample optiimze resolution results (required)"
  ),
  make_option(c("-o", "--output"),
              action = "store", default = NA, type = "character",
              help = "Output directory, will create if it doesn't exist (required)"
  ),
  make_option(c("--output_prefix"),
              action = "store",
              default = "optimize_resolution",
              type = "character",
              help = "Prefix for output files, [default %default]"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

# Check if required args are provided
if (is.na(opt$input) | is.na(opt$output)) {
  stop("Missing one or more required arguments")
}


# Load required packages --------------------------------------------------
library(tidyverse)

# Prevent the Rplots.pdf from being autogenerated
pdf(NULL)

# create the results folders and all parent folders if they don't exist
if (!(dir.exists(opt$output))) {
  dir.create(opt$output, recursive = TRUE)
}


# Initialize variables & read in data -------------------------------------
# list of all files
files_per_sample <- list.files(opt$input, pattern = ".csv", full.names = T)

# Read all files
res_tbl <- bind_rows(lapply(files_per_sample, read.csv))


# Summarize results
results_summary <- res_tbl %>%
  group_by(resolution) %>%
  summarize(
    mean_score = mean(avg_width, na.rm = TRUE),
    variance_score = var(avg_width, na.rm = TRUE),
    standard_error_score = sd(avg_width, na.rm = TRUE) / sqrt(length(avg_width)),
    cluster_mean_score = mean(cluster_avg_widths, na.rm = TRUE),
    cluster_variance_score = var(cluster_avg_widths, na.rm = TRUE),
    cluster_standard_error_score = sd(cluster_avg_widths,na.rm = TRUE) / sqrt(length(cluster_avg_widths))
  )


# Generate outputs --------------------------------------------------------

write_csv(
  x = res_tbl,
  file = paste0(
    opt$output,
    "/",
    opt$output_prefix,
    "_results_full.csv"
  )
)

write_csv(
  x = results_summary,
  file = paste0(
    opt$output,
    "/",
    opt$output_prefix,
    "_results_summary.csv"
  )
)

res_tbl %>%
  drop_na() %>%
  ggplot(aes(x = as.factor(resolution), y = avg_width)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Resolution", y = "Avg. Silhouette Score Across All Cells")

ggsave(filename = paste0(
  opt$output,
  "/",
  opt$output_prefix,
  "_avg_width_boxplot.png"
))

res_tbl %>%
  drop_na() %>%
  ggplot(aes(x = as.factor(resolution), y = cluster_avg_widths)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Resolution", y = "Avg. Silhouette Score Across Clusters")

ggsave(filename = paste0(
  opt$output,
  "/",
  opt$output_prefix,
  "_cluster_avg_width_boxplot.png"
))

ggplot(
  results_summary,
  aes(x = as.factor(resolution), y = mean_score, group = 1)
) +
  geom_errorbar(
    aes(
      ymin = mean_score - (1.96*standard_error_score),
      ymax = mean_score + (1.96*standard_error_score),
      width = .3
    ),
    color = "red"
  ) +
  geom_point(colour = "#619CFF") +
  geom_line(colour = "#619CFF") +
  theme_bw() +
  labs(x = "Resolution", y = "Avg. Silhouette Score Across All Cells")

ggsave(filename = paste0(
  opt$output,
  "/",
  opt$output_prefix,
  "_avg_width_95_percent_confidence_interval.png"
))

ggplot(
  results_summary,
  aes(x = as.factor(resolution), y = cluster_mean_score, group = 1) # scale should be the res range
) +
  geom_errorbar(
    aes(
      ymin = cluster_mean_score - (1.96*cluster_standard_error_score),
      ymax = cluster_mean_score + (1.96*cluster_standard_error_score),
      width = .3
    ),
    color = "red"
  ) +
  geom_point(colour = "#619CFF") +
  geom_line(colour = "#619CFF") +
  theme_bw() +
  labs(x = "Resolution", y = "Avg. Silhouette Score Across Clusters")

ggsave(filename = paste0(
  opt$output,
  "/",
  opt$output_prefix,
  "_cluster_avg_width_95_percent_confidence_interval.png"
))



writeLines(
  capture.output(sessionInfo()),
  file.path(opt$output, "sessionInfo.txt")
)


# END ---------------------------------------------------------------------